codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "proto/**/*.pb.go"
  - "**/*_gen.go"
  - "test/**"
  - "cmd/**"

flags:
  unittests:
    paths:
      - pkg/
    carryforward: true
